// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: opentelemetry/proto/logs/v1/logs.proto

package io.opentelemetry.proto.logs.v1;

/**
 * <pre>
 * A collection of ScopeLogs from a Resource.
 * </pre>
 *
 * Protobuf type {@code opentelemetry.proto.logs.v1.ResourceLogs}
 */
public final class ResourceLogs extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:opentelemetry.proto.logs.v1.ResourceLogs)
    ResourceLogsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ResourceLogs.newBuilder() to construct.
  private ResourceLogs(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ResourceLogs() {
    scopeLogs_ = java.util.Collections.emptyList();
    schemaUrl_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new ResourceLogs();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ResourceLogs(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            io.opentelemetry.proto.resource.v1.Resource.Builder subBuilder = null;
            if (resource_ != null) {
              subBuilder = resource_.toBuilder();
            }
            resource_ = input.readMessage(io.opentelemetry.proto.resource.v1.Resource.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(resource_);
              resource_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              scopeLogs_ = new java.util.ArrayList<ScopeLogs>();
              mutable_bitField0_ |= 0x00000001;
            }
            scopeLogs_.add(
                input.readMessage(ScopeLogs.parser(), extensionRegistry));
            break;
          }
          case 26: {
            String s = input.readStringRequireUtf8();

            schemaUrl_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        scopeLogs_ = java.util.Collections.unmodifiableList(scopeLogs_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return LogsProto.internal_static_opentelemetry_proto_logs_v1_ResourceLogs_descriptor;
  }

  @Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return LogsProto.internal_static_opentelemetry_proto_logs_v1_ResourceLogs_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ResourceLogs.class, Builder.class);
  }

  public static final int RESOURCE_FIELD_NUMBER = 1;
  private io.opentelemetry.proto.resource.v1.Resource resource_;
  /**
   * <pre>
   * The resource for the logs in this message.
   * If this field is not set then resource info is unknown.
   * </pre>
   *
   * <code>.opentelemetry.proto.resource.v1.Resource resource = 1;</code>
   * @return Whether the resource field is set.
   */
  @Override
  public boolean hasResource() {
    return resource_ != null;
  }
  /**
   * <pre>
   * The resource for the logs in this message.
   * If this field is not set then resource info is unknown.
   * </pre>
   *
   * <code>.opentelemetry.proto.resource.v1.Resource resource = 1;</code>
   * @return The resource.
   */
  @Override
  public io.opentelemetry.proto.resource.v1.Resource getResource() {
    return resource_ == null ? io.opentelemetry.proto.resource.v1.Resource.getDefaultInstance() : resource_;
  }
  /**
   * <pre>
   * The resource for the logs in this message.
   * If this field is not set then resource info is unknown.
   * </pre>
   *
   * <code>.opentelemetry.proto.resource.v1.Resource resource = 1;</code>
   */
  @Override
  public io.opentelemetry.proto.resource.v1.ResourceOrBuilder getResourceOrBuilder() {
    return getResource();
  }

  public static final int SCOPE_LOGS_FIELD_NUMBER = 2;
  private java.util.List<ScopeLogs> scopeLogs_;
  /**
   * <pre>
   * A list of ScopeLogs that originate from a resource.
   * </pre>
   *
   * <code>repeated .opentelemetry.proto.logs.v1.ScopeLogs scope_logs = 2;</code>
   */
  @Override
  public java.util.List<ScopeLogs> getScopeLogsList() {
    return scopeLogs_;
  }
  /**
   * <pre>
   * A list of ScopeLogs that originate from a resource.
   * </pre>
   *
   * <code>repeated .opentelemetry.proto.logs.v1.ScopeLogs scope_logs = 2;</code>
   */
  @Override
  public java.util.List<? extends ScopeLogsOrBuilder>
      getScopeLogsOrBuilderList() {
    return scopeLogs_;
  }
  /**
   * <pre>
   * A list of ScopeLogs that originate from a resource.
   * </pre>
   *
   * <code>repeated .opentelemetry.proto.logs.v1.ScopeLogs scope_logs = 2;</code>
   */
  @Override
  public int getScopeLogsCount() {
    return scopeLogs_.size();
  }
  /**
   * <pre>
   * A list of ScopeLogs that originate from a resource.
   * </pre>
   *
   * <code>repeated .opentelemetry.proto.logs.v1.ScopeLogs scope_logs = 2;</code>
   */
  @Override
  public ScopeLogs getScopeLogs(int index) {
    return scopeLogs_.get(index);
  }
  /**
   * <pre>
   * A list of ScopeLogs that originate from a resource.
   * </pre>
   *
   * <code>repeated .opentelemetry.proto.logs.v1.ScopeLogs scope_logs = 2;</code>
   */
  @Override
  public ScopeLogsOrBuilder getScopeLogsOrBuilder(
      int index) {
    return scopeLogs_.get(index);
  }

  public static final int SCHEMA_URL_FIELD_NUMBER = 3;
  private volatile Object schemaUrl_;
  /**
   * <pre>
   * The Schema URL, if known. This is the identifier of the Schema that the resource data
   * is recorded in. Notably, the last part of the URL path is the version number of the
   * schema: http[s]://server[:port]/path/&lt;version&gt;. To learn more about Schema URL see
   * https://opentelemetry.io/docs/specs/otel/schemas/#schema-url
   * This schema_url applies to the data in the "resource" field. It does not apply
   * to the data in the "scope_logs" field which have their own schema_url field.
   * </pre>
   *
   * <code>string schema_url = 3;</code>
   * @return The schemaUrl.
   */
  @Override
  public String getSchemaUrl() {
    Object ref = schemaUrl_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      schemaUrl_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The Schema URL, if known. This is the identifier of the Schema that the resource data
   * is recorded in. Notably, the last part of the URL path is the version number of the
   * schema: http[s]://server[:port]/path/&lt;version&gt;. To learn more about Schema URL see
   * https://opentelemetry.io/docs/specs/otel/schemas/#schema-url
   * This schema_url applies to the data in the "resource" field. It does not apply
   * to the data in the "scope_logs" field which have their own schema_url field.
   * </pre>
   *
   * <code>string schema_url = 3;</code>
   * @return The bytes for schemaUrl.
   */
  @Override
  public com.google.protobuf.ByteString
      getSchemaUrlBytes() {
    Object ref = schemaUrl_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      schemaUrl_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (resource_ != null) {
      output.writeMessage(1, getResource());
    }
    for (int i = 0; i < scopeLogs_.size(); i++) {
      output.writeMessage(2, scopeLogs_.get(i));
    }
    if (!getSchemaUrlBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, schemaUrl_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (resource_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getResource());
    }
    for (int i = 0; i < scopeLogs_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, scopeLogs_.get(i));
    }
    if (!getSchemaUrlBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, schemaUrl_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ResourceLogs)) {
      return super.equals(obj);
    }
    ResourceLogs other = (ResourceLogs) obj;

    if (hasResource() != other.hasResource()) return false;
    if (hasResource()) {
      if (!getResource()
          .equals(other.getResource())) return false;
    }
    if (!getScopeLogsList()
        .equals(other.getScopeLogsList())) return false;
    if (!getSchemaUrl()
        .equals(other.getSchemaUrl())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasResource()) {
      hash = (37 * hash) + RESOURCE_FIELD_NUMBER;
      hash = (53 * hash) + getResource().hashCode();
    }
    if (getScopeLogsCount() > 0) {
      hash = (37 * hash) + SCOPE_LOGS_FIELD_NUMBER;
      hash = (53 * hash) + getScopeLogsList().hashCode();
    }
    hash = (37 * hash) + SCHEMA_URL_FIELD_NUMBER;
    hash = (53 * hash) + getSchemaUrl().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ResourceLogs parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ResourceLogs parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ResourceLogs parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ResourceLogs parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ResourceLogs parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ResourceLogs parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ResourceLogs parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ResourceLogs parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ResourceLogs parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ResourceLogs parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ResourceLogs parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ResourceLogs parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ResourceLogs prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * A collection of ScopeLogs from a Resource.
   * </pre>
   *
   * Protobuf type {@code opentelemetry.proto.logs.v1.ResourceLogs}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:opentelemetry.proto.logs.v1.ResourceLogs)
      ResourceLogsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return LogsProto.internal_static_opentelemetry_proto_logs_v1_ResourceLogs_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return LogsProto.internal_static_opentelemetry_proto_logs_v1_ResourceLogs_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ResourceLogs.class, Builder.class);
    }

    // Construct using io.opentelemetry.proto.logs.v1.ResourceLogs.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getScopeLogsFieldBuilder();
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      if (resourceBuilder_ == null) {
        resource_ = null;
      } else {
        resource_ = null;
        resourceBuilder_ = null;
      }
      if (scopeLogsBuilder_ == null) {
        scopeLogs_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        scopeLogsBuilder_.clear();
      }
      schemaUrl_ = "";

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return LogsProto.internal_static_opentelemetry_proto_logs_v1_ResourceLogs_descriptor;
    }

    @Override
    public ResourceLogs getDefaultInstanceForType() {
      return ResourceLogs.getDefaultInstance();
    }

    @Override
    public ResourceLogs build() {
      ResourceLogs result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public ResourceLogs buildPartial() {
      ResourceLogs result = new ResourceLogs(this);
      int from_bitField0_ = bitField0_;
      if (resourceBuilder_ == null) {
        result.resource_ = resource_;
      } else {
        result.resource_ = resourceBuilder_.build();
      }
      if (scopeLogsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          scopeLogs_ = java.util.Collections.unmodifiableList(scopeLogs_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.scopeLogs_ = scopeLogs_;
      } else {
        result.scopeLogs_ = scopeLogsBuilder_.build();
      }
      result.schemaUrl_ = schemaUrl_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ResourceLogs) {
        return mergeFrom((ResourceLogs)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ResourceLogs other) {
      if (other == ResourceLogs.getDefaultInstance()) return this;
      if (other.hasResource()) {
        mergeResource(other.getResource());
      }
      if (scopeLogsBuilder_ == null) {
        if (!other.scopeLogs_.isEmpty()) {
          if (scopeLogs_.isEmpty()) {
            scopeLogs_ = other.scopeLogs_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureScopeLogsIsMutable();
            scopeLogs_.addAll(other.scopeLogs_);
          }
          onChanged();
        }
      } else {
        if (!other.scopeLogs_.isEmpty()) {
          if (scopeLogsBuilder_.isEmpty()) {
            scopeLogsBuilder_.dispose();
            scopeLogsBuilder_ = null;
            scopeLogs_ = other.scopeLogs_;
            bitField0_ = (bitField0_ & ~0x00000001);
            scopeLogsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getScopeLogsFieldBuilder() : null;
          } else {
            scopeLogsBuilder_.addAllMessages(other.scopeLogs_);
          }
        }
      }
      if (!other.getSchemaUrl().isEmpty()) {
        schemaUrl_ = other.schemaUrl_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ResourceLogs parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ResourceLogs) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private io.opentelemetry.proto.resource.v1.Resource resource_;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.opentelemetry.proto.resource.v1.Resource, io.opentelemetry.proto.resource.v1.Resource.Builder, io.opentelemetry.proto.resource.v1.ResourceOrBuilder> resourceBuilder_;
    /**
     * <pre>
     * The resource for the logs in this message.
     * If this field is not set then resource info is unknown.
     * </pre>
     *
     * <code>.opentelemetry.proto.resource.v1.Resource resource = 1;</code>
     * @return Whether the resource field is set.
     */
    public boolean hasResource() {
      return resourceBuilder_ != null || resource_ != null;
    }
    /**
     * <pre>
     * The resource for the logs in this message.
     * If this field is not set then resource info is unknown.
     * </pre>
     *
     * <code>.opentelemetry.proto.resource.v1.Resource resource = 1;</code>
     * @return The resource.
     */
    public io.opentelemetry.proto.resource.v1.Resource getResource() {
      if (resourceBuilder_ == null) {
        return resource_ == null ? io.opentelemetry.proto.resource.v1.Resource.getDefaultInstance() : resource_;
      } else {
        return resourceBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * The resource for the logs in this message.
     * If this field is not set then resource info is unknown.
     * </pre>
     *
     * <code>.opentelemetry.proto.resource.v1.Resource resource = 1;</code>
     */
    public Builder setResource(io.opentelemetry.proto.resource.v1.Resource value) {
      if (resourceBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        resource_ = value;
        onChanged();
      } else {
        resourceBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * The resource for the logs in this message.
     * If this field is not set then resource info is unknown.
     * </pre>
     *
     * <code>.opentelemetry.proto.resource.v1.Resource resource = 1;</code>
     */
    public Builder setResource(
        io.opentelemetry.proto.resource.v1.Resource.Builder builderForValue) {
      if (resourceBuilder_ == null) {
        resource_ = builderForValue.build();
        onChanged();
      } else {
        resourceBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * The resource for the logs in this message.
     * If this field is not set then resource info is unknown.
     * </pre>
     *
     * <code>.opentelemetry.proto.resource.v1.Resource resource = 1;</code>
     */
    public Builder mergeResource(io.opentelemetry.proto.resource.v1.Resource value) {
      if (resourceBuilder_ == null) {
        if (resource_ != null) {
          resource_ =
            io.opentelemetry.proto.resource.v1.Resource.newBuilder(resource_).mergeFrom(value).buildPartial();
        } else {
          resource_ = value;
        }
        onChanged();
      } else {
        resourceBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * The resource for the logs in this message.
     * If this field is not set then resource info is unknown.
     * </pre>
     *
     * <code>.opentelemetry.proto.resource.v1.Resource resource = 1;</code>
     */
    public Builder clearResource() {
      if (resourceBuilder_ == null) {
        resource_ = null;
        onChanged();
      } else {
        resource_ = null;
        resourceBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * The resource for the logs in this message.
     * If this field is not set then resource info is unknown.
     * </pre>
     *
     * <code>.opentelemetry.proto.resource.v1.Resource resource = 1;</code>
     */
    public io.opentelemetry.proto.resource.v1.Resource.Builder getResourceBuilder() {
      
      onChanged();
      return getResourceFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * The resource for the logs in this message.
     * If this field is not set then resource info is unknown.
     * </pre>
     *
     * <code>.opentelemetry.proto.resource.v1.Resource resource = 1;</code>
     */
    public io.opentelemetry.proto.resource.v1.ResourceOrBuilder getResourceOrBuilder() {
      if (resourceBuilder_ != null) {
        return resourceBuilder_.getMessageOrBuilder();
      } else {
        return resource_ == null ?
            io.opentelemetry.proto.resource.v1.Resource.getDefaultInstance() : resource_;
      }
    }
    /**
     * <pre>
     * The resource for the logs in this message.
     * If this field is not set then resource info is unknown.
     * </pre>
     *
     * <code>.opentelemetry.proto.resource.v1.Resource resource = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.opentelemetry.proto.resource.v1.Resource, io.opentelemetry.proto.resource.v1.Resource.Builder, io.opentelemetry.proto.resource.v1.ResourceOrBuilder> 
        getResourceFieldBuilder() {
      if (resourceBuilder_ == null) {
        resourceBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.opentelemetry.proto.resource.v1.Resource, io.opentelemetry.proto.resource.v1.Resource.Builder, io.opentelemetry.proto.resource.v1.ResourceOrBuilder>(
                getResource(),
                getParentForChildren(),
                isClean());
        resource_ = null;
      }
      return resourceBuilder_;
    }

    private java.util.List<ScopeLogs> scopeLogs_ =
      java.util.Collections.emptyList();
    private void ensureScopeLogsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        scopeLogs_ = new java.util.ArrayList<ScopeLogs>(scopeLogs_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        ScopeLogs, ScopeLogs.Builder, ScopeLogsOrBuilder> scopeLogsBuilder_;

    /**
     * <pre>
     * A list of ScopeLogs that originate from a resource.
     * </pre>
     *
     * <code>repeated .opentelemetry.proto.logs.v1.ScopeLogs scope_logs = 2;</code>
     */
    public java.util.List<ScopeLogs> getScopeLogsList() {
      if (scopeLogsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(scopeLogs_);
      } else {
        return scopeLogsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * A list of ScopeLogs that originate from a resource.
     * </pre>
     *
     * <code>repeated .opentelemetry.proto.logs.v1.ScopeLogs scope_logs = 2;</code>
     */
    public int getScopeLogsCount() {
      if (scopeLogsBuilder_ == null) {
        return scopeLogs_.size();
      } else {
        return scopeLogsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * A list of ScopeLogs that originate from a resource.
     * </pre>
     *
     * <code>repeated .opentelemetry.proto.logs.v1.ScopeLogs scope_logs = 2;</code>
     */
    public ScopeLogs getScopeLogs(int index) {
      if (scopeLogsBuilder_ == null) {
        return scopeLogs_.get(index);
      } else {
        return scopeLogsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * A list of ScopeLogs that originate from a resource.
     * </pre>
     *
     * <code>repeated .opentelemetry.proto.logs.v1.ScopeLogs scope_logs = 2;</code>
     */
    public Builder setScopeLogs(
        int index, ScopeLogs value) {
      if (scopeLogsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureScopeLogsIsMutable();
        scopeLogs_.set(index, value);
        onChanged();
      } else {
        scopeLogsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * A list of ScopeLogs that originate from a resource.
     * </pre>
     *
     * <code>repeated .opentelemetry.proto.logs.v1.ScopeLogs scope_logs = 2;</code>
     */
    public Builder setScopeLogs(
        int index, ScopeLogs.Builder builderForValue) {
      if (scopeLogsBuilder_ == null) {
        ensureScopeLogsIsMutable();
        scopeLogs_.set(index, builderForValue.build());
        onChanged();
      } else {
        scopeLogsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * A list of ScopeLogs that originate from a resource.
     * </pre>
     *
     * <code>repeated .opentelemetry.proto.logs.v1.ScopeLogs scope_logs = 2;</code>
     */
    public Builder addScopeLogs(ScopeLogs value) {
      if (scopeLogsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureScopeLogsIsMutable();
        scopeLogs_.add(value);
        onChanged();
      } else {
        scopeLogsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * A list of ScopeLogs that originate from a resource.
     * </pre>
     *
     * <code>repeated .opentelemetry.proto.logs.v1.ScopeLogs scope_logs = 2;</code>
     */
    public Builder addScopeLogs(
        int index, ScopeLogs value) {
      if (scopeLogsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureScopeLogsIsMutable();
        scopeLogs_.add(index, value);
        onChanged();
      } else {
        scopeLogsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * A list of ScopeLogs that originate from a resource.
     * </pre>
     *
     * <code>repeated .opentelemetry.proto.logs.v1.ScopeLogs scope_logs = 2;</code>
     */
    public Builder addScopeLogs(
        ScopeLogs.Builder builderForValue) {
      if (scopeLogsBuilder_ == null) {
        ensureScopeLogsIsMutable();
        scopeLogs_.add(builderForValue.build());
        onChanged();
      } else {
        scopeLogsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * A list of ScopeLogs that originate from a resource.
     * </pre>
     *
     * <code>repeated .opentelemetry.proto.logs.v1.ScopeLogs scope_logs = 2;</code>
     */
    public Builder addScopeLogs(
        int index, ScopeLogs.Builder builderForValue) {
      if (scopeLogsBuilder_ == null) {
        ensureScopeLogsIsMutable();
        scopeLogs_.add(index, builderForValue.build());
        onChanged();
      } else {
        scopeLogsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * A list of ScopeLogs that originate from a resource.
     * </pre>
     *
     * <code>repeated .opentelemetry.proto.logs.v1.ScopeLogs scope_logs = 2;</code>
     */
    public Builder addAllScopeLogs(
        Iterable<? extends ScopeLogs> values) {
      if (scopeLogsBuilder_ == null) {
        ensureScopeLogsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, scopeLogs_);
        onChanged();
      } else {
        scopeLogsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * A list of ScopeLogs that originate from a resource.
     * </pre>
     *
     * <code>repeated .opentelemetry.proto.logs.v1.ScopeLogs scope_logs = 2;</code>
     */
    public Builder clearScopeLogs() {
      if (scopeLogsBuilder_ == null) {
        scopeLogs_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        scopeLogsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * A list of ScopeLogs that originate from a resource.
     * </pre>
     *
     * <code>repeated .opentelemetry.proto.logs.v1.ScopeLogs scope_logs = 2;</code>
     */
    public Builder removeScopeLogs(int index) {
      if (scopeLogsBuilder_ == null) {
        ensureScopeLogsIsMutable();
        scopeLogs_.remove(index);
        onChanged();
      } else {
        scopeLogsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * A list of ScopeLogs that originate from a resource.
     * </pre>
     *
     * <code>repeated .opentelemetry.proto.logs.v1.ScopeLogs scope_logs = 2;</code>
     */
    public ScopeLogs.Builder getScopeLogsBuilder(
        int index) {
      return getScopeLogsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * A list of ScopeLogs that originate from a resource.
     * </pre>
     *
     * <code>repeated .opentelemetry.proto.logs.v1.ScopeLogs scope_logs = 2;</code>
     */
    public ScopeLogsOrBuilder getScopeLogsOrBuilder(
        int index) {
      if (scopeLogsBuilder_ == null) {
        return scopeLogs_.get(index);  } else {
        return scopeLogsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * A list of ScopeLogs that originate from a resource.
     * </pre>
     *
     * <code>repeated .opentelemetry.proto.logs.v1.ScopeLogs scope_logs = 2;</code>
     */
    public java.util.List<? extends ScopeLogsOrBuilder>
         getScopeLogsOrBuilderList() {
      if (scopeLogsBuilder_ != null) {
        return scopeLogsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(scopeLogs_);
      }
    }
    /**
     * <pre>
     * A list of ScopeLogs that originate from a resource.
     * </pre>
     *
     * <code>repeated .opentelemetry.proto.logs.v1.ScopeLogs scope_logs = 2;</code>
     */
    public ScopeLogs.Builder addScopeLogsBuilder() {
      return getScopeLogsFieldBuilder().addBuilder(
          ScopeLogs.getDefaultInstance());
    }
    /**
     * <pre>
     * A list of ScopeLogs that originate from a resource.
     * </pre>
     *
     * <code>repeated .opentelemetry.proto.logs.v1.ScopeLogs scope_logs = 2;</code>
     */
    public ScopeLogs.Builder addScopeLogsBuilder(
        int index) {
      return getScopeLogsFieldBuilder().addBuilder(
          index, ScopeLogs.getDefaultInstance());
    }
    /**
     * <pre>
     * A list of ScopeLogs that originate from a resource.
     * </pre>
     *
     * <code>repeated .opentelemetry.proto.logs.v1.ScopeLogs scope_logs = 2;</code>
     */
    public java.util.List<ScopeLogs.Builder>
         getScopeLogsBuilderList() {
      return getScopeLogsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        ScopeLogs, ScopeLogs.Builder, ScopeLogsOrBuilder>
        getScopeLogsFieldBuilder() {
      if (scopeLogsBuilder_ == null) {
        scopeLogsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            ScopeLogs, ScopeLogs.Builder, ScopeLogsOrBuilder>(
                scopeLogs_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        scopeLogs_ = null;
      }
      return scopeLogsBuilder_;
    }

    private Object schemaUrl_ = "";
    /**
     * <pre>
     * The Schema URL, if known. This is the identifier of the Schema that the resource data
     * is recorded in. Notably, the last part of the URL path is the version number of the
     * schema: http[s]://server[:port]/path/&lt;version&gt;. To learn more about Schema URL see
     * https://opentelemetry.io/docs/specs/otel/schemas/#schema-url
     * This schema_url applies to the data in the "resource" field. It does not apply
     * to the data in the "scope_logs" field which have their own schema_url field.
     * </pre>
     *
     * <code>string schema_url = 3;</code>
     * @return The schemaUrl.
     */
    public String getSchemaUrl() {
      Object ref = schemaUrl_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        schemaUrl_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * The Schema URL, if known. This is the identifier of the Schema that the resource data
     * is recorded in. Notably, the last part of the URL path is the version number of the
     * schema: http[s]://server[:port]/path/&lt;version&gt;. To learn more about Schema URL see
     * https://opentelemetry.io/docs/specs/otel/schemas/#schema-url
     * This schema_url applies to the data in the "resource" field. It does not apply
     * to the data in the "scope_logs" field which have their own schema_url field.
     * </pre>
     *
     * <code>string schema_url = 3;</code>
     * @return The bytes for schemaUrl.
     */
    public com.google.protobuf.ByteString
        getSchemaUrlBytes() {
      Object ref = schemaUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        schemaUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The Schema URL, if known. This is the identifier of the Schema that the resource data
     * is recorded in. Notably, the last part of the URL path is the version number of the
     * schema: http[s]://server[:port]/path/&lt;version&gt;. To learn more about Schema URL see
     * https://opentelemetry.io/docs/specs/otel/schemas/#schema-url
     * This schema_url applies to the data in the "resource" field. It does not apply
     * to the data in the "scope_logs" field which have their own schema_url field.
     * </pre>
     *
     * <code>string schema_url = 3;</code>
     * @param value The schemaUrl to set.
     * @return This builder for chaining.
     */
    public Builder setSchemaUrl(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      schemaUrl_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The Schema URL, if known. This is the identifier of the Schema that the resource data
     * is recorded in. Notably, the last part of the URL path is the version number of the
     * schema: http[s]://server[:port]/path/&lt;version&gt;. To learn more about Schema URL see
     * https://opentelemetry.io/docs/specs/otel/schemas/#schema-url
     * This schema_url applies to the data in the "resource" field. It does not apply
     * to the data in the "scope_logs" field which have their own schema_url field.
     * </pre>
     *
     * <code>string schema_url = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearSchemaUrl() {
      
      schemaUrl_ = getDefaultInstance().getSchemaUrl();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The Schema URL, if known. This is the identifier of the Schema that the resource data
     * is recorded in. Notably, the last part of the URL path is the version number of the
     * schema: http[s]://server[:port]/path/&lt;version&gt;. To learn more about Schema URL see
     * https://opentelemetry.io/docs/specs/otel/schemas/#schema-url
     * This schema_url applies to the data in the "resource" field. It does not apply
     * to the data in the "scope_logs" field which have their own schema_url field.
     * </pre>
     *
     * <code>string schema_url = 3;</code>
     * @param value The bytes for schemaUrl to set.
     * @return This builder for chaining.
     */
    public Builder setSchemaUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      schemaUrl_ = value;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:opentelemetry.proto.logs.v1.ResourceLogs)
  }

  // @@protoc_insertion_point(class_scope:opentelemetry.proto.logs.v1.ResourceLogs)
  private static final ResourceLogs DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ResourceLogs();
  }

  public static ResourceLogs getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ResourceLogs>
      PARSER = new com.google.protobuf.AbstractParser<ResourceLogs>() {
    @Override
    public ResourceLogs parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ResourceLogs(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ResourceLogs> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<ResourceLogs> getParserForType() {
    return PARSER;
  }

  @Override
  public ResourceLogs getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

