// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: opentelemetry/proto/profiles/v1development/profiles.proto

package io.opentelemetry.proto.profiles.v1development;

/**
 * <pre>
 * ValueType describes the type and units of a value, with an optional aggregation temporality.
 * </pre>
 *
 * Protobuf type {@code opentelemetry.proto.profiles.v1development.ValueType}
 */
public final class ValueType extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:opentelemetry.proto.profiles.v1development.ValueType)
    ValueTypeOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ValueType.newBuilder() to construct.
  private ValueType(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ValueType() {
    aggregationTemporality_ = 0;
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new ValueType();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ValueType(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            typeStrindex_ = input.readInt32();
            break;
          }
          case 16: {

            unitStrindex_ = input.readInt32();
            break;
          }
          case 24: {
            int rawValue = input.readEnum();

            aggregationTemporality_ = rawValue;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ProfilesProto.internal_static_opentelemetry_proto_profiles_v1development_ValueType_descriptor;
  }

  @Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ProfilesProto.internal_static_opentelemetry_proto_profiles_v1development_ValueType_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ValueType.class, Builder.class);
  }

  public static final int TYPE_STRINDEX_FIELD_NUMBER = 1;
  private int typeStrindex_;
  /**
   * <pre>
   * Index into string table.
   * </pre>
   *
   * <code>int32 type_strindex = 1;</code>
   * @return The typeStrindex.
   */
  @Override
  public int getTypeStrindex() {
    return typeStrindex_;
  }

  public static final int UNIT_STRINDEX_FIELD_NUMBER = 2;
  private int unitStrindex_;
  /**
   * <pre>
   * Index into string table.
   * </pre>
   *
   * <code>int32 unit_strindex = 2;</code>
   * @return The unitStrindex.
   */
  @Override
  public int getUnitStrindex() {
    return unitStrindex_;
  }

  public static final int AGGREGATION_TEMPORALITY_FIELD_NUMBER = 3;
  private int aggregationTemporality_;
  /**
   * <code>.opentelemetry.proto.profiles.v1development.AggregationTemporality aggregation_temporality = 3;</code>
   * @return The enum numeric value on the wire for aggregationTemporality.
   */
  @Override public int getAggregationTemporalityValue() {
    return aggregationTemporality_;
  }
  /**
   * <code>.opentelemetry.proto.profiles.v1development.AggregationTemporality aggregation_temporality = 3;</code>
   * @return The aggregationTemporality.
   */
  @Override public AggregationTemporality getAggregationTemporality() {
    @SuppressWarnings("deprecation")
    AggregationTemporality result = AggregationTemporality.valueOf(aggregationTemporality_);
    return result == null ? AggregationTemporality.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (typeStrindex_ != 0) {
      output.writeInt32(1, typeStrindex_);
    }
    if (unitStrindex_ != 0) {
      output.writeInt32(2, unitStrindex_);
    }
    if (aggregationTemporality_ != AggregationTemporality.AGGREGATION_TEMPORALITY_UNSPECIFIED.getNumber()) {
      output.writeEnum(3, aggregationTemporality_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (typeStrindex_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, typeStrindex_);
    }
    if (unitStrindex_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, unitStrindex_);
    }
    if (aggregationTemporality_ != AggregationTemporality.AGGREGATION_TEMPORALITY_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, aggregationTemporality_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ValueType)) {
      return super.equals(obj);
    }
    ValueType other = (ValueType) obj;

    if (getTypeStrindex()
        != other.getTypeStrindex()) return false;
    if (getUnitStrindex()
        != other.getUnitStrindex()) return false;
    if (aggregationTemporality_ != other.aggregationTemporality_) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TYPE_STRINDEX_FIELD_NUMBER;
    hash = (53 * hash) + getTypeStrindex();
    hash = (37 * hash) + UNIT_STRINDEX_FIELD_NUMBER;
    hash = (53 * hash) + getUnitStrindex();
    hash = (37 * hash) + AGGREGATION_TEMPORALITY_FIELD_NUMBER;
    hash = (53 * hash) + aggregationTemporality_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ValueType parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ValueType parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ValueType parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ValueType parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ValueType parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ValueType parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ValueType parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ValueType parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ValueType parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ValueType parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ValueType parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ValueType parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ValueType prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * ValueType describes the type and units of a value, with an optional aggregation temporality.
   * </pre>
   *
   * Protobuf type {@code opentelemetry.proto.profiles.v1development.ValueType}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:opentelemetry.proto.profiles.v1development.ValueType)
      ValueTypeOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProfilesProto.internal_static_opentelemetry_proto_profiles_v1development_ValueType_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProfilesProto.internal_static_opentelemetry_proto_profiles_v1development_ValueType_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ValueType.class, Builder.class);
    }

    // Construct using io.opentelemetry.proto.profiles.v1development.ValueType.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      typeStrindex_ = 0;

      unitStrindex_ = 0;

      aggregationTemporality_ = 0;

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ProfilesProto.internal_static_opentelemetry_proto_profiles_v1development_ValueType_descriptor;
    }

    @Override
    public ValueType getDefaultInstanceForType() {
      return ValueType.getDefaultInstance();
    }

    @Override
    public ValueType build() {
      ValueType result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public ValueType buildPartial() {
      ValueType result = new ValueType(this);
      result.typeStrindex_ = typeStrindex_;
      result.unitStrindex_ = unitStrindex_;
      result.aggregationTemporality_ = aggregationTemporality_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ValueType) {
        return mergeFrom((ValueType)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ValueType other) {
      if (other == ValueType.getDefaultInstance()) return this;
      if (other.getTypeStrindex() != 0) {
        setTypeStrindex(other.getTypeStrindex());
      }
      if (other.getUnitStrindex() != 0) {
        setUnitStrindex(other.getUnitStrindex());
      }
      if (other.aggregationTemporality_ != 0) {
        setAggregationTemporalityValue(other.getAggregationTemporalityValue());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ValueType parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ValueType) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int typeStrindex_ ;
    /**
     * <pre>
     * Index into string table.
     * </pre>
     *
     * <code>int32 type_strindex = 1;</code>
     * @return The typeStrindex.
     */
    @Override
    public int getTypeStrindex() {
      return typeStrindex_;
    }
    /**
     * <pre>
     * Index into string table.
     * </pre>
     *
     * <code>int32 type_strindex = 1;</code>
     * @param value The typeStrindex to set.
     * @return This builder for chaining.
     */
    public Builder setTypeStrindex(int value) {
      
      typeStrindex_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Index into string table.
     * </pre>
     *
     * <code>int32 type_strindex = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTypeStrindex() {
      
      typeStrindex_ = 0;
      onChanged();
      return this;
    }

    private int unitStrindex_ ;
    /**
     * <pre>
     * Index into string table.
     * </pre>
     *
     * <code>int32 unit_strindex = 2;</code>
     * @return The unitStrindex.
     */
    @Override
    public int getUnitStrindex() {
      return unitStrindex_;
    }
    /**
     * <pre>
     * Index into string table.
     * </pre>
     *
     * <code>int32 unit_strindex = 2;</code>
     * @param value The unitStrindex to set.
     * @return This builder for chaining.
     */
    public Builder setUnitStrindex(int value) {
      
      unitStrindex_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Index into string table.
     * </pre>
     *
     * <code>int32 unit_strindex = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearUnitStrindex() {
      
      unitStrindex_ = 0;
      onChanged();
      return this;
    }

    private int aggregationTemporality_ = 0;
    /**
     * <code>.opentelemetry.proto.profiles.v1development.AggregationTemporality aggregation_temporality = 3;</code>
     * @return The enum numeric value on the wire for aggregationTemporality.
     */
    @Override public int getAggregationTemporalityValue() {
      return aggregationTemporality_;
    }
    /**
     * <code>.opentelemetry.proto.profiles.v1development.AggregationTemporality aggregation_temporality = 3;</code>
     * @param value The enum numeric value on the wire for aggregationTemporality to set.
     * @return This builder for chaining.
     */
    public Builder setAggregationTemporalityValue(int value) {
      
      aggregationTemporality_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.opentelemetry.proto.profiles.v1development.AggregationTemporality aggregation_temporality = 3;</code>
     * @return The aggregationTemporality.
     */
    @Override
    public AggregationTemporality getAggregationTemporality() {
      @SuppressWarnings("deprecation")
      AggregationTemporality result = AggregationTemporality.valueOf(aggregationTemporality_);
      return result == null ? AggregationTemporality.UNRECOGNIZED : result;
    }
    /**
     * <code>.opentelemetry.proto.profiles.v1development.AggregationTemporality aggregation_temporality = 3;</code>
     * @param value The aggregationTemporality to set.
     * @return This builder for chaining.
     */
    public Builder setAggregationTemporality(AggregationTemporality value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      aggregationTemporality_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.opentelemetry.proto.profiles.v1development.AggregationTemporality aggregation_temporality = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearAggregationTemporality() {
      
      aggregationTemporality_ = 0;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:opentelemetry.proto.profiles.v1development.ValueType)
  }

  // @@protoc_insertion_point(class_scope:opentelemetry.proto.profiles.v1development.ValueType)
  private static final ValueType DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ValueType();
  }

  public static ValueType getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ValueType>
      PARSER = new com.google.protobuf.AbstractParser<ValueType>() {
    @Override
    public ValueType parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ValueType(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ValueType> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<ValueType> getParserForType() {
    return PARSER;
  }

  @Override
  public ValueType getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

