// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: opentelemetry/proto/collector/profiles/v1development/profiles_service.proto

package io.opentelemetry.proto.collector.profiles.v1development;

/**
 * Protobuf type {@code opentelemetry.proto.collector.profiles.v1development.ExportProfilesServiceRequest}
 */
public final class ExportProfilesServiceRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:opentelemetry.proto.collector.profiles.v1development.ExportProfilesServiceRequest)
    ExportProfilesServiceRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ExportProfilesServiceRequest.newBuilder() to construct.
  private ExportProfilesServiceRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ExportProfilesServiceRequest() {
    resourceProfiles_ = java.util.Collections.emptyList();
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new ExportProfilesServiceRequest();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ExportProfilesServiceRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              resourceProfiles_ = new java.util.ArrayList<io.opentelemetry.proto.profiles.v1development.ResourceProfiles>();
              mutable_bitField0_ |= 0x00000001;
            }
            resourceProfiles_.add(
                input.readMessage(io.opentelemetry.proto.profiles.v1development.ResourceProfiles.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        resourceProfiles_ = java.util.Collections.unmodifiableList(resourceProfiles_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ProfilesServiceProto.internal_static_opentelemetry_proto_collector_profiles_v1development_ExportProfilesServiceRequest_descriptor;
  }

  @Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ProfilesServiceProto.internal_static_opentelemetry_proto_collector_profiles_v1development_ExportProfilesServiceRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ExportProfilesServiceRequest.class, Builder.class);
  }

  public static final int RESOURCE_PROFILES_FIELD_NUMBER = 1;
  private java.util.List<io.opentelemetry.proto.profiles.v1development.ResourceProfiles> resourceProfiles_;
  /**
   * <pre>
   * An array of ResourceProfiles.
   * For data coming from a single resource this array will typically contain one
   * element. Intermediary nodes (such as OpenTelemetry Collector) that receive
   * data from multiple origins typically batch the data before forwarding further and
   * in that case this array will contain multiple elements.
   * </pre>
   *
   * <code>repeated .opentelemetry.proto.profiles.v1development.ResourceProfiles resource_profiles = 1;</code>
   */
  @Override
  public java.util.List<io.opentelemetry.proto.profiles.v1development.ResourceProfiles> getResourceProfilesList() {
    return resourceProfiles_;
  }
  /**
   * <pre>
   * An array of ResourceProfiles.
   * For data coming from a single resource this array will typically contain one
   * element. Intermediary nodes (such as OpenTelemetry Collector) that receive
   * data from multiple origins typically batch the data before forwarding further and
   * in that case this array will contain multiple elements.
   * </pre>
   *
   * <code>repeated .opentelemetry.proto.profiles.v1development.ResourceProfiles resource_profiles = 1;</code>
   */
  @Override
  public java.util.List<? extends io.opentelemetry.proto.profiles.v1development.ResourceProfilesOrBuilder> 
      getResourceProfilesOrBuilderList() {
    return resourceProfiles_;
  }
  /**
   * <pre>
   * An array of ResourceProfiles.
   * For data coming from a single resource this array will typically contain one
   * element. Intermediary nodes (such as OpenTelemetry Collector) that receive
   * data from multiple origins typically batch the data before forwarding further and
   * in that case this array will contain multiple elements.
   * </pre>
   *
   * <code>repeated .opentelemetry.proto.profiles.v1development.ResourceProfiles resource_profiles = 1;</code>
   */
  @Override
  public int getResourceProfilesCount() {
    return resourceProfiles_.size();
  }
  /**
   * <pre>
   * An array of ResourceProfiles.
   * For data coming from a single resource this array will typically contain one
   * element. Intermediary nodes (such as OpenTelemetry Collector) that receive
   * data from multiple origins typically batch the data before forwarding further and
   * in that case this array will contain multiple elements.
   * </pre>
   *
   * <code>repeated .opentelemetry.proto.profiles.v1development.ResourceProfiles resource_profiles = 1;</code>
   */
  @Override
  public io.opentelemetry.proto.profiles.v1development.ResourceProfiles getResourceProfiles(int index) {
    return resourceProfiles_.get(index);
  }
  /**
   * <pre>
   * An array of ResourceProfiles.
   * For data coming from a single resource this array will typically contain one
   * element. Intermediary nodes (such as OpenTelemetry Collector) that receive
   * data from multiple origins typically batch the data before forwarding further and
   * in that case this array will contain multiple elements.
   * </pre>
   *
   * <code>repeated .opentelemetry.proto.profiles.v1development.ResourceProfiles resource_profiles = 1;</code>
   */
  @Override
  public io.opentelemetry.proto.profiles.v1development.ResourceProfilesOrBuilder getResourceProfilesOrBuilder(
      int index) {
    return resourceProfiles_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < resourceProfiles_.size(); i++) {
      output.writeMessage(1, resourceProfiles_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < resourceProfiles_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, resourceProfiles_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ExportProfilesServiceRequest)) {
      return super.equals(obj);
    }
    ExportProfilesServiceRequest other = (ExportProfilesServiceRequest) obj;

    if (!getResourceProfilesList()
        .equals(other.getResourceProfilesList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getResourceProfilesCount() > 0) {
      hash = (37 * hash) + RESOURCE_PROFILES_FIELD_NUMBER;
      hash = (53 * hash) + getResourceProfilesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ExportProfilesServiceRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ExportProfilesServiceRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ExportProfilesServiceRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ExportProfilesServiceRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ExportProfilesServiceRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ExportProfilesServiceRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ExportProfilesServiceRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ExportProfilesServiceRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ExportProfilesServiceRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ExportProfilesServiceRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ExportProfilesServiceRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ExportProfilesServiceRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ExportProfilesServiceRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code opentelemetry.proto.collector.profiles.v1development.ExportProfilesServiceRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:opentelemetry.proto.collector.profiles.v1development.ExportProfilesServiceRequest)
      ExportProfilesServiceRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProfilesServiceProto.internal_static_opentelemetry_proto_collector_profiles_v1development_ExportProfilesServiceRequest_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProfilesServiceProto.internal_static_opentelemetry_proto_collector_profiles_v1development_ExportProfilesServiceRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ExportProfilesServiceRequest.class, Builder.class);
    }

    // Construct using io.opentelemetry.proto.collector.profiles.v1development.ExportProfilesServiceRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getResourceProfilesFieldBuilder();
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      if (resourceProfilesBuilder_ == null) {
        resourceProfiles_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        resourceProfilesBuilder_.clear();
      }
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ProfilesServiceProto.internal_static_opentelemetry_proto_collector_profiles_v1development_ExportProfilesServiceRequest_descriptor;
    }

    @Override
    public ExportProfilesServiceRequest getDefaultInstanceForType() {
      return ExportProfilesServiceRequest.getDefaultInstance();
    }

    @Override
    public ExportProfilesServiceRequest build() {
      ExportProfilesServiceRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public ExportProfilesServiceRequest buildPartial() {
      ExportProfilesServiceRequest result = new ExportProfilesServiceRequest(this);
      int from_bitField0_ = bitField0_;
      if (resourceProfilesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          resourceProfiles_ = java.util.Collections.unmodifiableList(resourceProfiles_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.resourceProfiles_ = resourceProfiles_;
      } else {
        result.resourceProfiles_ = resourceProfilesBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ExportProfilesServiceRequest) {
        return mergeFrom((ExportProfilesServiceRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ExportProfilesServiceRequest other) {
      if (other == ExportProfilesServiceRequest.getDefaultInstance()) return this;
      if (resourceProfilesBuilder_ == null) {
        if (!other.resourceProfiles_.isEmpty()) {
          if (resourceProfiles_.isEmpty()) {
            resourceProfiles_ = other.resourceProfiles_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureResourceProfilesIsMutable();
            resourceProfiles_.addAll(other.resourceProfiles_);
          }
          onChanged();
        }
      } else {
        if (!other.resourceProfiles_.isEmpty()) {
          if (resourceProfilesBuilder_.isEmpty()) {
            resourceProfilesBuilder_.dispose();
            resourceProfilesBuilder_ = null;
            resourceProfiles_ = other.resourceProfiles_;
            bitField0_ = (bitField0_ & ~0x00000001);
            resourceProfilesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getResourceProfilesFieldBuilder() : null;
          } else {
            resourceProfilesBuilder_.addAllMessages(other.resourceProfiles_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ExportProfilesServiceRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ExportProfilesServiceRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<io.opentelemetry.proto.profiles.v1development.ResourceProfiles> resourceProfiles_ =
      java.util.Collections.emptyList();
    private void ensureResourceProfilesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        resourceProfiles_ = new java.util.ArrayList<io.opentelemetry.proto.profiles.v1development.ResourceProfiles>(resourceProfiles_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.opentelemetry.proto.profiles.v1development.ResourceProfiles, io.opentelemetry.proto.profiles.v1development.ResourceProfiles.Builder, io.opentelemetry.proto.profiles.v1development.ResourceProfilesOrBuilder> resourceProfilesBuilder_;

    /**
     * <pre>
     * An array of ResourceProfiles.
     * For data coming from a single resource this array will typically contain one
     * element. Intermediary nodes (such as OpenTelemetry Collector) that receive
     * data from multiple origins typically batch the data before forwarding further and
     * in that case this array will contain multiple elements.
     * </pre>
     *
     * <code>repeated .opentelemetry.proto.profiles.v1development.ResourceProfiles resource_profiles = 1;</code>
     */
    public java.util.List<io.opentelemetry.proto.profiles.v1development.ResourceProfiles> getResourceProfilesList() {
      if (resourceProfilesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(resourceProfiles_);
      } else {
        return resourceProfilesBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * An array of ResourceProfiles.
     * For data coming from a single resource this array will typically contain one
     * element. Intermediary nodes (such as OpenTelemetry Collector) that receive
     * data from multiple origins typically batch the data before forwarding further and
     * in that case this array will contain multiple elements.
     * </pre>
     *
     * <code>repeated .opentelemetry.proto.profiles.v1development.ResourceProfiles resource_profiles = 1;</code>
     */
    public int getResourceProfilesCount() {
      if (resourceProfilesBuilder_ == null) {
        return resourceProfiles_.size();
      } else {
        return resourceProfilesBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * An array of ResourceProfiles.
     * For data coming from a single resource this array will typically contain one
     * element. Intermediary nodes (such as OpenTelemetry Collector) that receive
     * data from multiple origins typically batch the data before forwarding further and
     * in that case this array will contain multiple elements.
     * </pre>
     *
     * <code>repeated .opentelemetry.proto.profiles.v1development.ResourceProfiles resource_profiles = 1;</code>
     */
    public io.opentelemetry.proto.profiles.v1development.ResourceProfiles getResourceProfiles(int index) {
      if (resourceProfilesBuilder_ == null) {
        return resourceProfiles_.get(index);
      } else {
        return resourceProfilesBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * An array of ResourceProfiles.
     * For data coming from a single resource this array will typically contain one
     * element. Intermediary nodes (such as OpenTelemetry Collector) that receive
     * data from multiple origins typically batch the data before forwarding further and
     * in that case this array will contain multiple elements.
     * </pre>
     *
     * <code>repeated .opentelemetry.proto.profiles.v1development.ResourceProfiles resource_profiles = 1;</code>
     */
    public Builder setResourceProfiles(
        int index, io.opentelemetry.proto.profiles.v1development.ResourceProfiles value) {
      if (resourceProfilesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureResourceProfilesIsMutable();
        resourceProfiles_.set(index, value);
        onChanged();
      } else {
        resourceProfilesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * An array of ResourceProfiles.
     * For data coming from a single resource this array will typically contain one
     * element. Intermediary nodes (such as OpenTelemetry Collector) that receive
     * data from multiple origins typically batch the data before forwarding further and
     * in that case this array will contain multiple elements.
     * </pre>
     *
     * <code>repeated .opentelemetry.proto.profiles.v1development.ResourceProfiles resource_profiles = 1;</code>
     */
    public Builder setResourceProfiles(
        int index, io.opentelemetry.proto.profiles.v1development.ResourceProfiles.Builder builderForValue) {
      if (resourceProfilesBuilder_ == null) {
        ensureResourceProfilesIsMutable();
        resourceProfiles_.set(index, builderForValue.build());
        onChanged();
      } else {
        resourceProfilesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * An array of ResourceProfiles.
     * For data coming from a single resource this array will typically contain one
     * element. Intermediary nodes (such as OpenTelemetry Collector) that receive
     * data from multiple origins typically batch the data before forwarding further and
     * in that case this array will contain multiple elements.
     * </pre>
     *
     * <code>repeated .opentelemetry.proto.profiles.v1development.ResourceProfiles resource_profiles = 1;</code>
     */
    public Builder addResourceProfiles(io.opentelemetry.proto.profiles.v1development.ResourceProfiles value) {
      if (resourceProfilesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureResourceProfilesIsMutable();
        resourceProfiles_.add(value);
        onChanged();
      } else {
        resourceProfilesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * An array of ResourceProfiles.
     * For data coming from a single resource this array will typically contain one
     * element. Intermediary nodes (such as OpenTelemetry Collector) that receive
     * data from multiple origins typically batch the data before forwarding further and
     * in that case this array will contain multiple elements.
     * </pre>
     *
     * <code>repeated .opentelemetry.proto.profiles.v1development.ResourceProfiles resource_profiles = 1;</code>
     */
    public Builder addResourceProfiles(
        int index, io.opentelemetry.proto.profiles.v1development.ResourceProfiles value) {
      if (resourceProfilesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureResourceProfilesIsMutable();
        resourceProfiles_.add(index, value);
        onChanged();
      } else {
        resourceProfilesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * An array of ResourceProfiles.
     * For data coming from a single resource this array will typically contain one
     * element. Intermediary nodes (such as OpenTelemetry Collector) that receive
     * data from multiple origins typically batch the data before forwarding further and
     * in that case this array will contain multiple elements.
     * </pre>
     *
     * <code>repeated .opentelemetry.proto.profiles.v1development.ResourceProfiles resource_profiles = 1;</code>
     */
    public Builder addResourceProfiles(
        io.opentelemetry.proto.profiles.v1development.ResourceProfiles.Builder builderForValue) {
      if (resourceProfilesBuilder_ == null) {
        ensureResourceProfilesIsMutable();
        resourceProfiles_.add(builderForValue.build());
        onChanged();
      } else {
        resourceProfilesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * An array of ResourceProfiles.
     * For data coming from a single resource this array will typically contain one
     * element. Intermediary nodes (such as OpenTelemetry Collector) that receive
     * data from multiple origins typically batch the data before forwarding further and
     * in that case this array will contain multiple elements.
     * </pre>
     *
     * <code>repeated .opentelemetry.proto.profiles.v1development.ResourceProfiles resource_profiles = 1;</code>
     */
    public Builder addResourceProfiles(
        int index, io.opentelemetry.proto.profiles.v1development.ResourceProfiles.Builder builderForValue) {
      if (resourceProfilesBuilder_ == null) {
        ensureResourceProfilesIsMutable();
        resourceProfiles_.add(index, builderForValue.build());
        onChanged();
      } else {
        resourceProfilesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * An array of ResourceProfiles.
     * For data coming from a single resource this array will typically contain one
     * element. Intermediary nodes (such as OpenTelemetry Collector) that receive
     * data from multiple origins typically batch the data before forwarding further and
     * in that case this array will contain multiple elements.
     * </pre>
     *
     * <code>repeated .opentelemetry.proto.profiles.v1development.ResourceProfiles resource_profiles = 1;</code>
     */
    public Builder addAllResourceProfiles(
        Iterable<? extends io.opentelemetry.proto.profiles.v1development.ResourceProfiles> values) {
      if (resourceProfilesBuilder_ == null) {
        ensureResourceProfilesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, resourceProfiles_);
        onChanged();
      } else {
        resourceProfilesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * An array of ResourceProfiles.
     * For data coming from a single resource this array will typically contain one
     * element. Intermediary nodes (such as OpenTelemetry Collector) that receive
     * data from multiple origins typically batch the data before forwarding further and
     * in that case this array will contain multiple elements.
     * </pre>
     *
     * <code>repeated .opentelemetry.proto.profiles.v1development.ResourceProfiles resource_profiles = 1;</code>
     */
    public Builder clearResourceProfiles() {
      if (resourceProfilesBuilder_ == null) {
        resourceProfiles_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        resourceProfilesBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * An array of ResourceProfiles.
     * For data coming from a single resource this array will typically contain one
     * element. Intermediary nodes (such as OpenTelemetry Collector) that receive
     * data from multiple origins typically batch the data before forwarding further and
     * in that case this array will contain multiple elements.
     * </pre>
     *
     * <code>repeated .opentelemetry.proto.profiles.v1development.ResourceProfiles resource_profiles = 1;</code>
     */
    public Builder removeResourceProfiles(int index) {
      if (resourceProfilesBuilder_ == null) {
        ensureResourceProfilesIsMutable();
        resourceProfiles_.remove(index);
        onChanged();
      } else {
        resourceProfilesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * An array of ResourceProfiles.
     * For data coming from a single resource this array will typically contain one
     * element. Intermediary nodes (such as OpenTelemetry Collector) that receive
     * data from multiple origins typically batch the data before forwarding further and
     * in that case this array will contain multiple elements.
     * </pre>
     *
     * <code>repeated .opentelemetry.proto.profiles.v1development.ResourceProfiles resource_profiles = 1;</code>
     */
    public io.opentelemetry.proto.profiles.v1development.ResourceProfiles.Builder getResourceProfilesBuilder(
        int index) {
      return getResourceProfilesFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * An array of ResourceProfiles.
     * For data coming from a single resource this array will typically contain one
     * element. Intermediary nodes (such as OpenTelemetry Collector) that receive
     * data from multiple origins typically batch the data before forwarding further and
     * in that case this array will contain multiple elements.
     * </pre>
     *
     * <code>repeated .opentelemetry.proto.profiles.v1development.ResourceProfiles resource_profiles = 1;</code>
     */
    public io.opentelemetry.proto.profiles.v1development.ResourceProfilesOrBuilder getResourceProfilesOrBuilder(
        int index) {
      if (resourceProfilesBuilder_ == null) {
        return resourceProfiles_.get(index);  } else {
        return resourceProfilesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * An array of ResourceProfiles.
     * For data coming from a single resource this array will typically contain one
     * element. Intermediary nodes (such as OpenTelemetry Collector) that receive
     * data from multiple origins typically batch the data before forwarding further and
     * in that case this array will contain multiple elements.
     * </pre>
     *
     * <code>repeated .opentelemetry.proto.profiles.v1development.ResourceProfiles resource_profiles = 1;</code>
     */
    public java.util.List<? extends io.opentelemetry.proto.profiles.v1development.ResourceProfilesOrBuilder> 
         getResourceProfilesOrBuilderList() {
      if (resourceProfilesBuilder_ != null) {
        return resourceProfilesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(resourceProfiles_);
      }
    }
    /**
     * <pre>
     * An array of ResourceProfiles.
     * For data coming from a single resource this array will typically contain one
     * element. Intermediary nodes (such as OpenTelemetry Collector) that receive
     * data from multiple origins typically batch the data before forwarding further and
     * in that case this array will contain multiple elements.
     * </pre>
     *
     * <code>repeated .opentelemetry.proto.profiles.v1development.ResourceProfiles resource_profiles = 1;</code>
     */
    public io.opentelemetry.proto.profiles.v1development.ResourceProfiles.Builder addResourceProfilesBuilder() {
      return getResourceProfilesFieldBuilder().addBuilder(
          io.opentelemetry.proto.profiles.v1development.ResourceProfiles.getDefaultInstance());
    }
    /**
     * <pre>
     * An array of ResourceProfiles.
     * For data coming from a single resource this array will typically contain one
     * element. Intermediary nodes (such as OpenTelemetry Collector) that receive
     * data from multiple origins typically batch the data before forwarding further and
     * in that case this array will contain multiple elements.
     * </pre>
     *
     * <code>repeated .opentelemetry.proto.profiles.v1development.ResourceProfiles resource_profiles = 1;</code>
     */
    public io.opentelemetry.proto.profiles.v1development.ResourceProfiles.Builder addResourceProfilesBuilder(
        int index) {
      return getResourceProfilesFieldBuilder().addBuilder(
          index, io.opentelemetry.proto.profiles.v1development.ResourceProfiles.getDefaultInstance());
    }
    /**
     * <pre>
     * An array of ResourceProfiles.
     * For data coming from a single resource this array will typically contain one
     * element. Intermediary nodes (such as OpenTelemetry Collector) that receive
     * data from multiple origins typically batch the data before forwarding further and
     * in that case this array will contain multiple elements.
     * </pre>
     *
     * <code>repeated .opentelemetry.proto.profiles.v1development.ResourceProfiles resource_profiles = 1;</code>
     */
    public java.util.List<io.opentelemetry.proto.profiles.v1development.ResourceProfiles.Builder> 
         getResourceProfilesBuilderList() {
      return getResourceProfilesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.opentelemetry.proto.profiles.v1development.ResourceProfiles, io.opentelemetry.proto.profiles.v1development.ResourceProfiles.Builder, io.opentelemetry.proto.profiles.v1development.ResourceProfilesOrBuilder> 
        getResourceProfilesFieldBuilder() {
      if (resourceProfilesBuilder_ == null) {
        resourceProfilesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            io.opentelemetry.proto.profiles.v1development.ResourceProfiles, io.opentelemetry.proto.profiles.v1development.ResourceProfiles.Builder, io.opentelemetry.proto.profiles.v1development.ResourceProfilesOrBuilder>(
                resourceProfiles_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        resourceProfiles_ = null;
      }
      return resourceProfilesBuilder_;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:opentelemetry.proto.collector.profiles.v1development.ExportProfilesServiceRequest)
  }

  // @@protoc_insertion_point(class_scope:opentelemetry.proto.collector.profiles.v1development.ExportProfilesServiceRequest)
  private static final ExportProfilesServiceRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ExportProfilesServiceRequest();
  }

  public static ExportProfilesServiceRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ExportProfilesServiceRequest>
      PARSER = new com.google.protobuf.AbstractParser<ExportProfilesServiceRequest>() {
    @Override
    public ExportProfilesServiceRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ExportProfilesServiceRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ExportProfilesServiceRequest> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<ExportProfilesServiceRequest> getParserForType() {
    return PARSER;
  }

  @Override
  public ExportProfilesServiceRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

