// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: opentelemetry/proto/collector/profiles/v1development/profiles_service.proto

package io.opentelemetry.proto.collector.profiles.v1development;

public final class ProfilesServiceProto {
  private ProfilesServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opentelemetry_proto_collector_profiles_v1development_ExportProfilesServiceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opentelemetry_proto_collector_profiles_v1development_ExportProfilesServiceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opentelemetry_proto_collector_profiles_v1development_ExportProfilesServiceResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opentelemetry_proto_collector_profiles_v1development_ExportProfilesServiceResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opentelemetry_proto_collector_profiles_v1development_ExportProfilesPartialSuccess_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opentelemetry_proto_collector_profiles_v1development_ExportProfilesPartialSuccess_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\nKopentelemetry/proto/collector/profiles" +
      "/v1development/profiles_service.proto\0224o" +
      "pentelemetry.proto.collector.profiles.v1" +
      "development\0329opentelemetry/proto/profile" +
      "s/v1development/profiles.proto\"w\n\034Export" +
      "ProfilesServiceRequest\022W\n\021resource_profi" +
      "les\030\001 \003(\0132<.opentelemetry.proto.profiles" +
      ".v1development.ResourceProfiles\"\214\001\n\035Expo" +
      "rtProfilesServiceResponse\022k\n\017partial_suc" +
      "cess\030\001 \001(\0132R.opentelemetry.proto.collect" +
      "or.profiles.v1development.ExportProfiles" +
      "PartialSuccess\"P\n\034ExportProfilesPartialS" +
      "uccess\022\031\n\021rejected_profiles\030\001 \001(\003\022\025\n\rerr" +
      "or_message\030\002 \001(\t2\307\001\n\017ProfilesService\022\263\001\n" +
      "\006Export\022R.opentelemetry.proto.collector." +
      "profiles.v1development.ExportProfilesSer" +
      "viceRequest\032S.opentelemetry.proto.collec" +
      "tor.profiles.v1development.ExportProfile" +
      "sServiceResponse\"\000B\311\001\n7io.opentelemetry." +
      "proto.collector.profiles.v1developmentB\024" +
      "ProfilesServiceProtoP\001Z?go.opentelemetry" +
      ".io/proto/otlp/collector/profiles/v1deve" +
      "lopment\252\0024OpenTelemetry.Proto.Collector." +
      "Profiles.V1Developmentb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          io.opentelemetry.proto.profiles.v1development.ProfilesProto.getDescriptor(),
        });
    internal_static_opentelemetry_proto_collector_profiles_v1development_ExportProfilesServiceRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_opentelemetry_proto_collector_profiles_v1development_ExportProfilesServiceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opentelemetry_proto_collector_profiles_v1development_ExportProfilesServiceRequest_descriptor,
        new String[] { "ResourceProfiles", });
    internal_static_opentelemetry_proto_collector_profiles_v1development_ExportProfilesServiceResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_opentelemetry_proto_collector_profiles_v1development_ExportProfilesServiceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opentelemetry_proto_collector_profiles_v1development_ExportProfilesServiceResponse_descriptor,
        new String[] { "PartialSuccess", });
    internal_static_opentelemetry_proto_collector_profiles_v1development_ExportProfilesPartialSuccess_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_opentelemetry_proto_collector_profiles_v1development_ExportProfilesPartialSuccess_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opentelemetry_proto_collector_profiles_v1development_ExportProfilesPartialSuccess_descriptor,
        new String[] { "RejectedProfiles", "ErrorMessage", });
    io.opentelemetry.proto.profiles.v1development.ProfilesProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
